name: Build Release

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  build:

    env:
      SOLUTION: 'Ubiq.Fourcasters.sln'
      VERSION_PREFIX: '1.0.3'
 
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run:  |
            dotnet nuget add source "https://nuget.pkg.github.com/UbiqAnalytics/index.json" --name "github" --username "ubiqbuild" --password "${{ secrets.ACCESS_TOKEN }}" --store-password-in-clear-text
            dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration Release --no-restore /p:VersionPrefix=${{ env.VERSION_PREFIX }}

    - name: Run tests
      run: dotnet test /p:Configuration=Release --no-restore --no-build --verbosity normal

    - name: publish package Fourcasters
      run: dotnet nuget push "Ubiq.FourcastersAPI/bin/Release/Ubiq.FourcastersAPI.${{ env.VERSION_PREFIX }}.nupkg" --api-key ${{ secrets.ACCESS_TOKEN }} --source "github"
